---
- hosts: database
  roles:
    - mysql

- hosts: wordpress
  roles:
    - webserver
    - wordpress


# Sintaxe mais de versões mais antiga do Ansible para loop
# - hosts: all
#   tasks:
#     - name: 'Instala pacotes de depencia do sistema operacional'
#       apt:
#         name: "{{ item }}"
#         state: latest
#       become: yes
#       with_items:
#         - php5
#         - apache2
#         - libapache2-mod-php5
#         - php5-gd
#         - libssh2-php
#         - php5-mcrypt
#         - mysql-server-5.6
#         - python-mysqldb
#         - php5-mysql
